disabled_rules:
  - function_body_length
  - line_length
  - force_try
  - variable_name_min_length
  - type_body_length
  - control_statement
  - file_length
excluded:
  - Pods
  - R.generated.swift

