source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'RxSwift', '~> 2.0.0-beta'
pod 'RxCocoa', '~> 2.0.0-beta'
pod 'RxBlocking', '~> 2.0.0-beta'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Kingfisher', '~> 1.8.2'
pod 'RongCloudIMKit', '~> 2.4.1'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'Bugly'
pod 'RealmSwift'
